### ISSUE TITLE
Don't compile

### ISSUE THREAD

**Issue by xsobolx** [davinctor/CompileFFmpegWithOpenSSL#5]
Finished with: ERROR: openssl not found

**Comment by davinctor** [comment]
Hi, @xsobolx, thanks for your report.
Could you provide your steps and your environment (OS, OS version, etc)?

**Comment by davinctor** [comment]
By the way, this error can happen on different NDK version, so, please provide your NDK version.

Also check your `libs/ffmpeg/binaries` and `libs/openssl/build` directories. If they aren't empty - compilation finished with success for some architectures, but failed only for some other architectures (check [README](https://github.com/davinctor/CompileFFmpegWithOpenSSL#ps))

**Comment by xsobolx** [comment]
I tried on MacOs X El Capitan 10.11.15 and Ubuntu 16.10 NDK r14b from this site[https://developer.android.com/ndk/downloads/index.html](url)
Directories are empty

**Comment by davinctor** [comment]
@xsobolx , update [this](https://github.com/davinctor/CompileFFmpegWithOpenSSL/blob/master/build.sh#L3) file and provide your path to NDK
```
#!/bin/sh

export NDK=YOUR PATH TO NDK
export WORKING_DIR=`pwd`

TARGET_ARMEABI_DIR=$WORKING_DIR/armeabi
TARGET_ARMEABIV7A_DIR=$WORKING_DIR/armeabi-v7a
```
